# Generated by Django 4.2.1 on 2023-05-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_event_supportteam_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesteam',
            options={'verbose_name': 'SalesTeam'},
        ),
    ]
