# Generated by Django 4.2.1 on 2023-05-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_alter_salesteam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportteam',
            options={'verbose_name': 'SupportTeam'},
        ),
    ]
