# Generated by Django 4.2.1 on 2023-05-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client'},
        ),
    ]
