# Generated by Django 4.2.1 on 2023-05-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_alter_client_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
