# Generated by Django 4.2.1 on 2023-05-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
