# Generated by Django 4.2.1 on 2023-05-31 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_delete_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.event')),
            ],
        ),
    ]
