# Generated by Django 4.2.1 on 2023-05-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_potential',
            field=models.BooleanField(default=True),
        ),
    ]
