# Generated by Django 4.2.1 on 2023-05-31 12:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0012_client_is_potential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='SalesContact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.salesteam'),
        ),
        migrations.AddField(
            model_name='client',
            name='companyname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 5, 31, 12, 14, 44, 746496, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='firstname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lastname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='mobil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
