# Generated by Django 4.2.1 on 2023-05-31 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0013_remove_client_name_client_salescontact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='event',
        ),
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 31, 12, 21, 30, 809851, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='salesContact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CRM.salesteam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
